import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Centralny szpital spierdolenia",
  description: "Generated by create next app",
  icons: {
    icon: "/zdjecia/logo.jpg", 
  },
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 569fde63fcd67f3f07967f05d1b3c4750bf9719a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
